### ISSUE TITLE
Erro when launch preproc.py?

### ISSUE THREAD

**Issue by crankler** [anranli2003/KinfuROS#1]
Hi, thanks for share the fastsam combined pkg.
When I launch preproc, the error shows:
```
Traceback (most recent call last):
  File "src/KinfuROS/seg_preproc/scripts/preproc.py", line 161, in <module>
    main()
  File "src/KinfuROS/seg_preproc/scripts/preproc.py", line 152, in main
    Preproc(**params)
  File "src/KinfuROS/seg_preproc/scripts/preproc.py", line 44, in __init__
    self.segformer_trt = SegFormerTRT(segformer_trt_file, segformer_taxonomy)
  File "/home/yc/catkin_map/catkin_michgen/src/KinfuROS/seg_preproc/utils/segformer_trt.py", line 23, in __init__
    self.input_dims = self.engine.get_binding_shape(0)
AttributeError: 'NoneType' object has no attribute 'get_binding_shape'
Exception ignored in: <function SegFormerTRT.__del__ at 0x7f2ae0e48a60>
Traceback (most recent call last):
  File "/home/yc/catkin_map/catkin_michgen/src/KinfuROS/seg_preproc/utils/segformer_trt.py", line 31, in __del__
    del self.d_input
AttributeError: d_input

```

Can you tell me how to fix it?

Moreover, I note there exist onnx2trt.py and trt_engine_8.6.1.trt, should I rerun it?
I still see the error when I run ```python3 src/KinfuROS/seg_preproc/scripts/onnx2trt.py ```

**Comment by anranli2003** [comment]
Hey there, the only file you need to run for the preprocessing part is the preproc.py in the scripts folder. And in terms of the error you provided above, could you provide some more information on it? For example, how you ran it, what your system setup is etc.
